### ISSUE TITLE
Upload on Modrinth Please

### ISSUE THREAD

**Issue by sternschnaube** [GrigLog/RoughlyEnoughTrades#2]
https://modrinth.com/

**Comment by GrigLog** [comment]
How is it better than CurseForge?

**Comment by venaminecraft** [comment]
A Search- and Notification function which works... 😆
To mention just two of the biggest issues on Curse.
Bigger audience.

**Comment by GrigLog** [comment]
Done

**Comment by venaminecraft** [comment]
Thank you 😊
